# Generated by Django 5.2.8 on 2025-11-26 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iventaris_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='peminjaman',
            name='status_peminjaman',
            field=models.CharField(choices=[('aktif', 'Aktif (Sedang Dipinjam)'), ('selesai', 'Selesai (Sudah Dikembalikan)')], default='aktif', max_length=10),
        ),
    ]
